language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/phpunit -c ./phpunit.no_autoload.xml
